sudo: false
language: node_js
cache:
  directories:
    - node_modules
branches:
  only:
    - master
notifications:
  email: false
node_js:
  - '5'
  - '4'
  - iojs-v3
  - iojs-v2
  - iojs-v1
  - '0.12'
  - '0.10'
before_install:
  - npm i -g npm@^3.3.0
before_script:
  - npm prune
script:
  - npm run test:single
  - npm run build
